### ISSUE TITLE
Exiting VBE (Visual Basic Editor) debug mode restarts workspacer

### ISSUE THREAD

**Issue by N1x0** [rickbutton/workspacer#117]
So the title basically sums it up. If you write some code in the VBE in excel or Word all works fine. You go into debug mode and things stay good. However when you **exit** debug mode (when the little pop-up comes) workspacer does a full restart.

**Comment by josteink** [comment]
If you build Workspacer from source, and run it in Visual Studio in debug-mode, you can enable [Break on all exceptions](https://christianfindlay.com/2019/07/14/visual-studio-break-on-all-exceptions/) (not just uncaught ones).

If you can trigger this error-condition while running workspacer in debug-mode, you might be able to get a stack-trace and pinpoint where the error occurs.

From there it should hopefully be quite easy to location the cause of the error and fix it.

**Comment by N1x0** [comment]
Thank you for your kind suggestion @josteink , however I think this one's an open-and-shut case... The keyboard shortcut to close VBE is `alt+q` which I didn't know is the same one to restart workspacer. Issue was fixed by reassigning the shortcut 😅 .

**Comment by josteink** [comment]
Glad you figured it out 😅
