### ISSUE TITLE
Handle applications that focus another window

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#12]
Eg, if I click a link in my email application that launches in my browser, then currently workspacer eats the "focus browser" action and it flashes for a split second then doesn't do anything.

It should indicate somehow that another application was attempted to be focused.

This could be focusing the workspace that application belongs to or it could be just flashing that workspace in the title bar or something else. As long as there is some obvious indication

**Comment by rickbutton** [comment]
this should be fixed now, the behavior is that a window is focused that isn't in a visible workspace, we will force the workspace onto the desired monitor. I tested this with firefox via:

```
 "C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -new-tab https://google.com
```
with firefox in another workspace it seems to work well
