### ISSUE TITLE
Duplicate keybinds for: toggle enable/disable workspacer

### ISSUE THREAD

**Issue by N1x0** [rickbutton/workspacer#121]
I was wondering why the `toggle enable/disable` function (which is rather essential IMO) didn't work for me and found that there's a duplicate key binding in `\workspacer\src\workspacer\Keybinds\KeyBindManager.cs` 

 `mod + LShift + E`  is being being assigned to two actions
**Line 209** -  `_context.Enabled = !_context.Enabled, "toggle enable/disable");`
**Line 309** -  `_context.Workspaces.MoveFocusedWindowToMonitor(1), "move focused window to monitor 2");`

The docs on the website also claim that `mod + LShift + E` is used for toggling so might want to edit those as well

**Comment by josteink** [comment]
Good find!￼

Maybe we should also add some warnings to the logs when re-binding already bound keys to easier catch situations like these?

**Comment by N1x0** [comment]
Yeah it definitely should show up somewhere. I'll have a look at how those are done and create a PR to include if @rickbutton agrees

**Comment by josteink** [comment]
No need to wait for Rick. I approve, and I can get PRs merged :smile:

**Comment by N1x0** [comment]
So I looked through the `KeyBindManager` and based on my (very limited) understanding of C# it would require a bit of a rewrite. At the moment key-binds are stored in  the **Dictionary** `_kbdSubs` so there is no real way to check for duplicates as the dictionary does not allow them in the first place.  A possible workaround could be to use a list with something like this:

```csharp
List<KeyValuePair<Sub, NamedBind<KeybindHandler>>> _kbdSubs = new List<KeyValuePair<Sub, NamedBind<KeybindHandler>>>();
```
Then it'd be easy to check for duplicates and add those to the logs as as Debug or even Fatal.

I'm happy to give this a try but not sure if there isn't an easier way or if I've missed something so any comments would be appreciated

**Comment by rickbutton** [comment]
> Yeah it definitely should show up somewhere. I'll have a look at how those are done and create a PR to include if @rickbutton agrees

sounds great, please do!


> So I looked through the `KeyBindManager` and based on my (very limited) understanding of C# it would require a bit of a rewrite. At the moment key-binds are stored in the **Dictionary** `_kbdSubs` so there is no real way to check for duplicates as the dictionary does not allow them in the first place. A possible workaround could be to use a list with something like this:

what if we made `KeyBindManager` throw if you attempt to bind a key that is already bound. this would mean that in order to  rebind a key, you would need to unbind it first. thoughts?
