### ISSUE TITLE
Is there UWP Support for Tiling?

### ISSUE THREAD

**Issue by lauverityhill** [rickbutton/workspacer#138]
Sorry, I'm a bit of a casual user. I was wondering if there is UWP support, since applications like OneNote, Calculator, and Groove Music don't tile (all of which are UWP apps). Also, UWP apps don't obey Workspace number as well (it's as if they are invisible to the window manager).

P.S.: Thank you for this piece of software!

**Comment by N1x0** [comment]
So I have no encountered your issues with the mentioned UWP apps as all three tile just fine for me. However there has been a documented issues with Power BI (another UWP app) which just closes when trying to hide it, see #97 . So there might be more limitations to it than just the lack of support for ` SW_HIDE `.

**Comment by lauverityhill** [comment]
Sorry for the late reply. Thank you @N1x0!

I have downloaded a Workspacer config here on github, and their configuration had a filter on class "ApplicationFrameWindow", which is what I think is the culprit.
