### ISSUE TITLE
Support for IconFonts (Bar)

### ISSUE THREAD

**Issue by N1x0** [rickbutton/workspacer#152]
So I've played around a bit with trying to get icons into the Bar and have had some degree of success. I've used [this](https://github.com/dkrusky/FontAwesome-For-WinForms-CSharp) to go about it. Basically all there was to it was to add the `Fonts.cs` file to `workspacer.Bar` solution and add the `.ttf` filepath. Edit: the Font needs to be installed system-wide as well. Just double clicking will call the installer so it's not a lot of additional work. Potentially the font could be packaged as content/resource file to circumvent this.

From there you can add icons to any part of the bar by just providing the name `Fonts.fa.Icon_Name`. This works for workspaces too!
![Annotation 2020-12-10 140712](https://user-images.githubusercontent.com/47623143/101733891-1bedd480-3af2-11eb-92e1-8bd7532e7933.jpg)

Now this only works if that font is selected for the entire bar (e.g. setting ` FontName = "FontAwesome"`), so that's a bit of drag, but I personally like having icons even if they're just eye-candy so I'd be happy to play with it a bit more and see if it's possible to have two fonts.

Curious to hear what people think, if it's interesting enough I'd be happy to make a PR

**Comment by josteink** [comment]
Font-awesome licensing seems a bit complex: https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt

Is it OK to bundle it with workspacer as is?

**Comment by N1x0** [comment]
I hadn't really considered that, from a first glance there don't seem to be any issues but I think I'll have to read it thoroughly to be sure.

**Comment by lauverityhill** [comment]
> Curious to hear what people think, if it's interesting enough I'd be happy to make a PR
I'm interested, please do!

**Comment by lauverityhill** [comment]
> Curious to hear what people think, if it's interesting enough I'd be happy to make a PR

I'm interested, please do!

**Comment by N1x0** [comment]
After some more testing there's two things necessary to make this work well I think. First the font file currently used is quite old so I'll prepare an equivalent with the much more recent Font Awesome 5 Free version. 
Secondly, and more important, to do this have a proper implementation it's necessary that each `Widget` can be assigned it's own font. Otherwise all widgets will take the icon font and the result looks weird (screenshot below)

![image](https://user-images.githubusercontent.com/47623143/101872033-2cb44e00-3bb7-11eb-988e-cfe575658399.png)

I quickly did this by adding another property `string Fontname` to each widget and adding the following to the `BarSection` method `SetLabel`. 

```csharp
 if(part.FontName != null)
            {
                label.Font = CreateFont(part.FontName, _fontSize);
            };
```

If there are no objections to this approach, I will PR this as a stand-alone feature and follow it up with the icon font in a separate PR.

**Comment by josteink** [comment]
> If there are no objections to this approach, I will PR this as a stand-alone feature and follow it up with the icon font in a separate PR.

That's sounds like the only proper way to do things :+1:

**Comment by BeeryShklar** [comment]
Would be very nice to also have an option for font families.

**Comment by projectoneuniverse** [comment]
> After some more testing there's two things necessary to make this work well I think. First the font file currently used is quite old so I'll prepare an equivalent with the much more recent Font Awesome 5 Free version.
> Secondly, and more important, for this to have a proper implementation it's necessary that each `Widget` can be assigned it's own font. Otherwise all widgets will take the icon font and the result looks weird (screenshot below)
> 
> ![image](https://user-images.githubusercontent.com/47623143/101872033-2cb44e00-3bb7-11eb-988e-cfe575658399.png)
> 
> I quickly did this by adding another property `string Fontname` to each widget and adding the following to the `BarSection` method `SetLabel`.
> 
> ```cs
>  if(part.FontName != null)
>             {
>                 label.Font = CreateFont(part.FontName, _fontSize);
>             };
> ```
> 
> If there are no objections to this approach, I will PR this as a stand-alone feature and follow it up with the icon font in a separate PR.

Sorry out off topic, but I try change default key binding not success.
How can i change the default key binding?
I tried with
KeyModifiers mod = KeyModifiers.Alt;
context.Keybinds.Subscribe (mod, Keys.T, () => context.Keybinds.Subscribe (mod, Keys.I));

But an error message appears:
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (27,78): error CS1503: Argument 1: cannot convert from 'workspacer.KeyModifiers' to 'workspacer.MouseEvent'

**Comment by josteink** [comment]
That is clearly off-topic and shouldn't be discussed in this issue.
