### ISSUE TITLE
Automatic Update issues

### ISSUE THREAD

**Issue by N1x0** [rickbutton/workspacer#153]
So workspacer should have automatic updates which is provided through the `AutoUpdater.NET` `NuGet` package. However I'm not sure if that is working as intended. 

The following is implemented in `\workspacer\src\workspacer\Program.cs`:

```csharp
#if BRANCH_unstable
            var branch = "unstable";
#elif BRANCH_stable 
            var branch = "stable";
#else
            string branch = null;
#endif
            if (branch != null)
            {
                var xmlUrl = $"https://workspacer.blob.core.windows.net/installers/{branch}.xml";

                AutoUpdater.ApplicationExitEvent += QuitForUpdate;

                System.Timers.Timer timer = new System.Timers.Timer(1000 * 60 * 60);
                timer.Elapsed += (s, e) =>
                {
                    AutoUpdater.Start(xmlUrl);
                };
                timer.Enabled = true;
                AutoUpdater.Start(xmlUrl);
            }
```

Maybe I didn't look carefully enough but I couldn't find a preprocessor directive for either `BRANCH_unstable` or `BRANCH_stable` meaning the check for updates never happens because `branch`will always evaluate to `null`. I tested this by editing the Assembly Version and the update does trigger correctly when the directives are present. I still don't quite understand the purpose of the 1hr timer though...

A second potential issue is that the user has no way of configuring this behaviour without going into the source files. I think it'd be nice to have this accessible through the config file instead. 

A a side note would implementing checksums for the downloads be possible? Would be nice if there's a way verify the integrity of the download prior to execution.

Happy to write something up for this if there's interest to have this feature.

**Comment by josteink** [comment]
> Maybe I didn't look carefully enough but I couldn't find a preprocessor directive for either BRANCH_unstable or BRANCH_stable

I may be wrong, but I believe those can be added to the msbuild command-line when building. Meaning it's the *builder* who decides what branch this is.

> I still don't quite understand the purpose of the 1hr timer though...

If I were to guess it would be to allow for a 1 hour of "oops I messed up" window to fix errors or retract builds.

> A second potential issue is that the user has no way of configuring this behaviour without going into the source files. I think it'd be nice to have this accessible through the config file instead.

Agreed. That sounds fairly reasonable. If something is set via the config-file, it should override whatever is set by the build itself.

Material for PR?

**Comment by rickbutton** [comment]
these compiler directives are automatically applied by the build pipeline (Azure Pipelines). I need to get around to switching that infra to GitHub Actions, which will make this more obvious (#80)
