### ISSUE TITLE
Unable to get the current count of workspaces

### ISSUE THREAD

**Issue by alex-griffiths** [rickbutton/workspacer#157]
I'm trying to subscribe a keyboard shortcut that creates a new workspace that is just an increment of the current number of workspaces. I had this working about a month ago, but I lost my config and didn't have it backed up.

I tried using `context.WorkspaceContainer.GetAllWorkspaces().ToList()` but I get an error about "IEnumerable<IWorkspace> does not contain a definition for ToList. 

My idea is that I'd get the total number of all workspaces, and then create a new string with that value + 1 that I can then just create a new workspace with. Something like this

```cs
// Register Alt+Shift+N to create a new workspace
var num_workspaces = context.WorkspaceContainer.GetAllWorkspaces().ToList().Count;
context.Keybinds.Subscribe(mod | KeyModifiers.LShift, Keys.N, () => {		
	context.WorkspaceContainer.CreateWorkspace((num_workspaces + 1).ToString());
}, "Create new workspace");
```

Any help with this would be appreciated.

**Comment by josteink** [comment]
> context.WorkspaceContainer.GetAllWorkspaces().ToList() but I get an error about "IEnumerable does not contain a definition for ToList.

ToList() is a LInQ extension method available via the `System.Linq` namespace.

**Comment by josteink** [comment]
On a sidenote, you don't need to do `.ToList().Count`. You can do `.Count()` directly.

**Comment by alex-griffiths** [comment]
Fantastic. Thanks so much.
