### ISSUE TITLE
Bar sizing error

### ISSUE THREAD

**Issue by NeoNlAmp3** [rickbutton/workspacer#169]
Hi,

I encountered a bug where the bar on my 3th display is set by another thread during first rendering.
![BarScaling](https://user-images.githubusercontent.com/64272175/103827878-39bf4280-507a-11eb-84e0-42a96e176ed9.PNG)

The issue happens in worspacer.Bar => BarForm.cs Line 67
By moving the position of the this.Width ? _monitor.With assignment to the bottom, the issue is fixed.

I don't know how the Contribution policy is, if needed I can create a branch an push the fix.

FYI: I'm running 3 monitors (HD,2,5k,4k)

**Comment by josteink** [comment]
> I don't know how the Contribution policy

Pretty much be a nice guy, test your changes and make a PR :smile:
