### ISSUE TITLE
UnsubscribeAll

### ISSUE THREAD

**Issue by evanricard** [rickbutton/workspacer#179]
Is there any way to unbind or rebind the alt-P command? Thanks!

**Comment by dalyIsaac** [comment]
https://github.com/rickbutton/workspacer/blob/0aaff4437222e471ea0ffd282b948a9dfb8b7ff5/snippets/custom_action_menu.cs#L2-L14

**Comment by evanricard** [comment]
Ooh .. thanks :)

**Comment by N1x0** [comment]
Here also a bit more general approach for any keybind
``` csharp
var mod = Keymodifiers.Alt;
context.Keybinds.Unsubscribe(mod, Keys.P);
context.Keybinds.Subscribe(mod, Keys.P, () => YOUR ACTION HERE, "optional description");

```

**Comment by evanricard** [comment]
Thanks @N1x0 ! Gonna close this
