### ISSUE TITLE
Expose extra process/window information to allow finer-grained sorting rules

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#23]
I have my config full of workspace selector func rules, but they're all just based off of the window title.

Per our conversation, it sounds like there is extra metadata that could be exposed to get finer-grained control over where each window should go.

**Comment by rickbutton** [comment]
In 0.8.3 I've exposed more or less everything you can reliably use to identify a window.

I've also added a way to view this info for a window (or all windows) with keybinds. By default, `alt-o` will open a text file with this metadata for all windows, while `alt-shift-o` will open the same metadata, but only for the window under the cursor.  The metadata looks like this:

```
#############################
window.Handle                    = 197318
window.Title                     = ""
window.Class                     = "Shell_TrayWnd"
window.Process.Id                = 31716
window.Process.ProcessName       = "explorer"
window.ProcessFileName           = "explorer.exe"
#############################
```

The right hand side is a description of how to access the value on a window.

**Comment by scottopell** [comment]
Does this still work? I don't see anything output in the console
