### ISSUE TITLE
Add some kind of console for debugging config files

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#34]
Writing anything non-trivial in your config is currently painful due to the lack of any debug console.

It would be extra great if I could set breakpoints in vscode and have it work at workspacer runtime :)

**Comment by rickbutton** [comment]
5ca75ebec8e9c77fa2ad4ff45587d06ce16a0506

you can set log level via (these are also the defaults):

```
context.ConsoleLogLevel = LogLevel.Info;
context.FileLogLevel = LogLevel.Warn;
```

You can force open/close the console via `alt-shift-i`, or call `context.ToggleConsoleWindow`

finally, I've removed the code that opens notepad for the window metadata dump, and instead am just outputting it to the console.
