### ISSUE TITLE
Workspacer should remember my focused window when switching workspaces

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#36]
If I have focus in window B on workspace X, when I'm switching to workspace Y and back to X, workspacer should net set focus in window A on workspace X.
It should remember where I had my focus when I left workspace X and set that window.

**Comment by rickbutton** [comment]
this should already be the behavior as of v0.9.0. can you check again with the latest version?

**Comment by rickbutton** [comment]
verified that this is how it works now, closing
