### ISSUE TITLE
Difficults to create a custom config

### ISSUE THREAD

**Issue by spadino** [rickbutton/workspacer#51]
Hi, @rickbutton! I'm fiddling with workspacer by some days. I want to populate a custom config, to suit my needs, but I can get to work only the workspaces configuration (how many and how they are named). Anything else - keybinds, routes, filter... - seems broken, as they do not allow workspacer to compile the config at startup.

Can you help my figuring out what I'm doing wrong?

For example:
```context.Keybinds.Subscribe(KeyModifiers.LWin, Keys.NumPad1, ()  => context.Workspaces.SwitchToWorkspace(0), "switch to workspace 1");```

should work, as well as 
```
context.WindowRouter.AddRoute((window) => window.Title.Contains("Visual Studio Code") ? context.WorkspaceContainer["7"] : null));

context.WindowRouter.AddRoute((window) => window.Title.Contains("Microsoft Visual Studio") ? context.WorkspaceContainer["8"] : null));
```

yet nothing seems to let workspacer accept my config. All them are inside doConfig = (context) =>

**Comment by rickbutton** [comment]
Yeah, error handling in general could be a lot better than it is right now.

Does the "exception dialog" show up on restart? If so, can you post the actual exception you are getting?
