### ISSUE TITLE
Make workspaces belong to monitors

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#6]
My mental model for how I would like my tiling window manager to work is as follows:
- Every workspace has a monitor associated with it
- Switching to a workspace would bring it into focus on its assigned monitor

Conceptually, I imagine this as each monitor having multiple screens and I'm switching between the screens within the monitor.

This fits my workflow of always keeping certain apps on certain monitors and being able to easily switch between them.

**Comment by rickbutton** [comment]
this is implemented in master, likely a part of v0.6.

as a part of my eventual quickstart / docs I will write up a description of all of the moving bits here, but the short snippet now is:

all workspace selection and monitor selection logic has been moved into IWorkspaceContainer, which is an interface that IWorkspaceManager uses to do its business.

WorkspaceContainer is the default, and is used by default (the new config will show creating a container and passing it to the workspace manager)

StickyWorkspaceContainer is the new version, that allows for the assignment of workspaces to specific monitors. it has two indexing modes (StickyWorkspaceIndexMode), Local, and Global (constructor options), that allows for addressing workspaces in this container local to the focused workspace, or global to the instance of workspacer.
