### ISSUE TITLE
Open to contributions? Code-review? Smallish design-nitpicks?

### ISSUE THREAD

**Issue by josteink** [rickbutton/workspacer#66]
Hey Rick!

I'm a reasonably seasoned C#-developer, an avid i3/sway user on Linux, but at work I have to use Windows. So this project definitely looks interesting to me.

With Digital Ocean's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) coming up, I thought I'd try to make some more *focused* efforts this year, rather than making drive-by PRs at random, unconnceted projects.

And workspacer definitely looks like something I can get working on. But I'm not going to invest too much of my time, unless I know it's appreciated or welcome.

So what I think I can contribute with fairly simply is (among other things):

- tighten up existing code, eliminate dead one.
- try to add more tests or code-doc
- make code adhere better to existing .NET conventions and patterns
- maybe even fix bugs, if they hit me enough to annoy me :smile: 
- etc

Sounds good? Should I consider all PRs welcome until otherwise noted? Let me know.

**Comment by rickbutton** [comment]
Hello!!!

Simply put: Yes Please!

I use `workspacer` every day, but haven't had time to work on it in months. There is a ton of room for improvement, from stability, to configuration interface, to documentation, to a proper test suite. I am open to contributions of all sizes!

For the next few weeks I'm drowning in work, but feel free to ask any questions / submit any PRs / open any issues, and I will help out as much as I can!

Thanks!

**Comment by josteink** [comment]
I'm starting on some drive-by code-cleanups right now, and then I started wondering... Would you like those all in one big PR...

Or should I separate them into smaller PRs where it's easier to review the individual cleanups? Any preferences?

**Comment by rickbutton** [comment]
Ideally smaller PRs that focus on a single issue/change are better (where practical of course).

**Comment by josteink** [comment]
You got it!

Some of the PRs are really, really small now, so let me know if you think it’s getting silly, and I’ll size them up.
