### ISSUE TITLE
Add more config snipperts that people would probably want

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#7]
Ignoring things like task manager by default is great, but there are a bunch of other good candidates in this list.

It would be great to have a list in the readme or something that I could submit a PR to.

Starting point:
```csharp
                if (window.Process.Id == Process.GetCurrentProcess().Id)
                    return false;
                if (window.Title.Contains("Task Manager"))
                    return false;
                if (window.Title == "Settings")
                    return false;
                if (window.Title == "Snipping Tool")
                    return false;
                if (window.Title.Contains("LICEcap"))
                    return false;
```

**Comment by rickbutton** [comment]
https://workspacer.org/config/

**Comment by rickbutton** [comment]
So this will essentially break up into two parts:

- snippets for general configuration (how to use a specific thing built into workspacer)
- snippets for program-specific configuration (how to make workspacer not break rando xyz app)

the former now lives in https://github.com/rickbutton/workspacer/tree/master/snippets

the latter will be tracked via #29
