### ISSUE TITLE
Preferred unit-test framework?

### ISSUE THREAD

**Issue by josteink** [rickbutton/workspacer#71]
Hey. 

I’m considering fixing up `Color.cs` next. And in doing so, I plan to add unit-tests for the problematic aspects I find. 

Soooo... do you have any preferred unit-test framework? MStest? Xunit? Nunit? Let me know, and I’ll stick to whatever you prefer. 

If you don’t have any opinion either way, I’ll probably prefer Xunit. Is that ok?

**Comment by rickbutton** [comment]
xunit is my preference as well! works for me

**Comment by josteink** [comment]
I usually employ the BDD way of creating tests: that is each method has a name which explicitly lays out a behaviour (Requesting_Config_For_Null_Workspace_Throws(), Hashcode_Does_Not_Collide(), Dispose_Can_Be_Repeatedly_As_Per_Convention(), etc). 

That way reading out the test-names alone becomes a semi-human readable spec for the functionality/class being tested. 

Is that an ok approach for workspacer too, or do you have other preferences?

**Comment by rickbutton** [comment]
yep, that seems fine to me!
