### ISSUE TITLE
Move from Azure Pipelines to GitHub Actions

### ISSUE THREAD

**Issue by rickbutton** [rickbutton/workspacer#80]
I'm currently using Azure Pipelines on my personal Azure account to setup automatic unstable builds/publish and the regular stable build/publish, as well as to deploy the website (via hugo). I should switch this to GitHub Actions (or at least investigate it!).

**Comment by josteink** [comment]
GitHub actions has gotten better... And Azure Pipelines has not. Also there's zero visibility on the GitHub end for PRs, current builds/actions etc.

Should we give this another go?

**Comment by josteink** [comment]
Also: I cannot see the new logo on the website after [this PR](https://github.com/rickbutton/workspacer/pull/145) was merged.

Are you sure your current pipelines are working as they should? (Again: Zero visibility for that on the Github end).
