### ISSUE TITLE
Create action bar similar to vscode

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#9]
In vscode, I can register keyboard shortcuts for various actions, but there are some that I don't do often enough to need a keyboard shortcut.

For this they have `ctrl+p` which opens a little action bar where I can search for and run various tasks.

This would be super useful to have so that I don't have to keep all the keyboard shortcuts in my head, or add a keyboard shortcut to my config for in-frequently used tasks

**Comment by rickbutton** [comment]
done! alt-p

I can flesh out the available menu options by default if more useful ones are found, but the API for adding them is rather simple so you can define as many infinitely nested menus as you want (see the new quickstart)

I have abstracted the query matching enough that the next step is to improve it and allow for fuzzy matching, but only partial string matching is implemented so far
