### ISSUE TITLE
Battery Indicator in the bar

### ISSUE THREAD

**Issue by MacAhmed** [rickbutton/workspacer#92]
Hiya,

I have been using workspacer for a while now. I like it quite a bit and have it set up so it basically fills all requirements. The only issue that I have right now is that since I hide the taskbar, I am unable to see the battery indicator. 

Is there a way to show battery percentage in the bar? 

Thankyou.

**Comment by rickbutton** [comment]
this sounds like a great case for a workspacer plugin. currently the docs aren't in a good place for how to do this, but I would gladly accept a PR for this feature.

**Comment by N1x0** [comment]
Hi @MacAhmed , 
Totally agree on your suggestion it'd be a great feature. Now I threw something together which works for me, but it is 
a) not compatible with every device
b) not feature-complete (it just shows a number and not even formatted as percentage)
c) requires additional assemblies (`system.management`)
Once I have worked this out a bit more I'll do a full PR, but for now I hope the code below is somewhat helpful to you.

```csharp

using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Management;
using System.Threading.Tasks;
using System.Timers;

namespace workspacer.Bar.Widgets
{
    public class BatteryWidget : BarWidgetBase
    {
        private Timer _timer;
        private int _interval;

        public BatteryWidget(int interval)
        {
            _interval = interval;
        }

        public static string GetBatteryPercentage()
        {
            ObjectQuery query = new ObjectQuery("Select * FROM Win32_Battery");
            ManagementObjectSearcher searcher = new ManagementObjectSearcher(query);

            ManagementObjectCollection collection = searcher.Get();

            foreach (ManagementObject mo in collection)
            {
                foreach (PropertyData property in mo.Properties)
                { 

                    if (property.Name == "EstimatedChargeRemaining")
                    {
                        return property.Value.ToString();
                    };
                }
            }
            return "NaN";
        }
        public BatteryWidget() : this(1000) { }

        public override IBarWidgetPart[] GetParts()
        {
            var percent = GetBatteryPercentage();
            return Parts(percent);
        }

        public override void Initialize()
        {
            _timer = new Timer(_interval);
            _timer.Elapsed += (s, e) => Context.MarkDirty();
            _timer.Enabled = true;
        }
    }
}

```

**Comment by MacAhmed** [comment]
@N1x0 

Thankyou so much for doing this. I started using it a few days ago and its been perfectly fine (figured I'd wait enough for the battery to go through its entire cycle). :) I took a look at the code and seems pretty good to me. I'd recommend to @rickbutton that it gets merged since its a useful default Widget to have 👍

**Comment by rickbutton** [comment]
Merged the PR, thanks for this suggestion!

**Comment by system32uwu** [comment]
Hi, how to enable this plugin? It's not covered in the docs

```c#
context.AddBar(new BarPluginConfig(){
    BarTitle = "workspacer.Bar",
    BarHeight = 20,
    FontSize = 12,
    FontName = "JetBrainsMono NF",
    DefaultWidgetForeground = Color.Blue,
    DefaultWidgetBackground = Color.White,
    Background = Color.White,
    //do I need to write Widgets = ["battery"] ? 
});
```

**Comment by flyxyz123** [comment]
> 
> 
> Hi, how to enable this plugin? It's not covered in the docs
> 
> ```cs
> context.AddBar(new BarPluginConfig(){
>     BarTitle = "workspacer.Bar",
>     BarHeight = 20,
>     FontSize = 12,
>     FontName = "JetBrainsMono NF",
>     DefaultWidgetForeground = Color.Blue,
>     DefaultWidgetBackground = Color.White,
>     Background = Color.White,
>     //RightWidgets = new IBarWidget[] { new TimeWidget(), new BatteryWidget() } 
> });
> ```

I think you just need to uncomment this line: `RightWidgets = new IBarWidget[] { new TimeWidget(), new BatteryWidget() }`
For example: <https://github.com/flyxyz123/config_local_win10/blob/56da3e0d467f98953aacd6ed8099daf4899a259a/.workspacer/workspacer.config.csx#L32>

**Comment by system32uwu** [comment]
> 
> 
> > Hi, how to enable this plugin? It's not covered in the docs
> > ```cs
> > context.AddBar(new BarPluginConfig(){
> >     BarTitle = "workspacer.Bar",
> >     BarHeight = 20,
> >     FontSize = 12,
> >     FontName = "JetBrainsMono NF",
> >     DefaultWidgetForeground = Color.Blue,
> >     DefaultWidgetBackground = Color.White,
> >     Background = Color.White,
> >     //RightWidgets = new IBarWidget[] { new TimeWidget(), new BatteryWidget() } 
> > });
> > ```
> 
> @system32uwu I think you just need to uncomment this line: `RightWidgets = new IBarWidget[] { new TimeWidget(), new BatteryWidget() }`
> For example: https://github.com/flyxyz123/config_local_win10/blob/56da3e0d467f98953aacd6ed8099daf4899a259a/.workspacer/workspacer.config.csx#L32

Hi, I commented that out because it was throwing an error, I read the source again and noticed it expects a function, so it's actually like this:
```c#
context.AddBar(new BarPluginConfig()
    {
        BarTitle = "workspacer.Bar",
        FontSize = 14,
        FontName = "JetBrainsMono NF",
        RightWidgets = () => new IBarWidget[] { new TimeWidget(), new BatteryWidget() },
    });
```
