### ISSUE TITLE
Typo in workspacer.org

### ISSUE THREAD

**Issue by takase1121** [rickbutton/workspacer#98]
Quoting from https://www.workspacer.org/config:
> the default configuration provides the standard set of ignore/routing rules, but more can be added via calls to AddFilter and AddRoute.
> 
> ```
># custom filter
> context.WindowRouter.AddFilter((window) => !window.Title.Contains("my fun application"));
> # custom route
> context.WindowRouter.AddRoute((window) => window.Title.Contains("Google Chrome") ? context.WorkspaceContainer["web"] : null));
> ```cs
>the AddFilter call will ensure that any windows who’s title contains the text “my fun application” will be ignored by workspacer. a true return value will allow the window to be managed, while a false value will force workspacer to ignore the window.

The line
```cs
context.WindowRouter.AddRoute((window) => window.Title.Contains("Google Chrome") ? context.WorkspaceContainer["web"] : null));
                                                                                                                           ^
                                                                                                                   Extra parenthesis
```

It throws a misleading error saying that it was missing a semicolon.
I know shouldn't copy the line as-is without reading but a typo is still a typo.

**Comment by josteink** [comment]
Agreed. Make a PR for it?

**Comment by takase1121** [comment]
Yeah when I have time

**Comment by rickbutton** [comment]
Thanks for this! I've fixed it.
